name: 编译FongMiTV
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4

      - name: 生成签名文件
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 -d > key.jks

      - name: 配置JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin

      - name: 写入签名配置
        run: |
          echo "storeFile=../key.jks" >> app/keystore.properties
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" >> app/keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> app/keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> app/keystore.properties

      - name: 开始编译
        run: chmod +x gradlew && ./gradlew assembleLeanbackRelease

      - name: 上传APK
        uses: actions/upload-artifact@v4
        with:
          name: FongMi-TV
          path: app/build/outputs/apk/leanback/release/*.apk
